name: Generate Snake Game

on:
  # Trigger the workflow on any push event to the main branch
  push:
    branches:
      - main
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate the Snake game from the GitHub contributions grid
      - name: Generate Snake game
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      # Step 3: Push the generated Snake game back to the repository
      - name: Commit and push Snake game
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Snake game"
          file_pattern: dist/snake.svg
